"""add is_active to users

Revision ID: 0e3ca5f3940e
Revises: bb3d3680b063
Create Date: 2026-08-21 01:23:43.592140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3ca5f3940e'
down_revision: Union[str, Sequence[str], None] = 'bb3d3680b063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_constraint(op.f('users_name_check'), 'users', type_='check')
    op.create_check_constraint('users_name_length_check', 'users', 'char_length(trim(name)) >= 2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_length_check', 'users', type_='check')
    op.create_check_constraint(op.f('users_name_check'), 'users', 'char_length(TRIM(BOTH FROM name)) >= 2')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
