"""add api key scopes

Revision ID: 894da094e290
Revises: 109256ae8eb8
Create Date: 2026-09-08 18:21:13.365748

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "894da094e290"
down_revision: str | Sequence[str] | None = "109256ae8eb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String(length=50)),
            server_default=sa.text("'{}'::character varying[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE api_keys
        SET scopes = ARRAY[
            'api-keys:read',
            'api-keys:write'
        ]::character varying[]
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "scopes")
    # ### end Alembic commands ###
