"""add transactional outbox

Revision ID: dd68f1425146
Revises: 397dffda8dfb
Create Date: 2026-09-10 23:18:41.866773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd68f1425146'
down_revision: Union[str, Sequence[str], None] = '397dffda8dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts >= 0', name='outbox_events_attempts_non_negative_check'),
    sa.CheckConstraint('char_length(trim(aggregate_type)) >= 1', name='outbox_events_aggregate_type_not_blank_check'),
    sa.CheckConstraint('char_length(trim(event_type)) >= 1', name='outbox_events_type_not_blank_check'),
    sa.CheckConstraint('event_version >= 1', name='outbox_events_version_positive_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_unpublished_created_at', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_unpublished_created_at', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
