"""add job idempotency keys

Revision ID: e13e045eeb8b
Revises: dd68f1425146
Create Date: 2026-09-19 15:14:08.772161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13e045eeb8b'
down_revision: Union[str, Sequence[str], None] = 'dd68f1425146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_idempotency_keys',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(idempotency_key) BETWEEN 1 AND 128', name='job_idempotency_keys_key_length_check'),
    sa.CheckConstraint('char_length(request_fingerprint) = 64', name='job_idempotency_keys_fingerprint_length_check'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_job_idempotency_keys_job_id_jobs', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_job_idempotency_keys_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_job_idempotency_keys_user_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_idempotency_keys')
    # ### end Alembic commands ###
