"""harden outbox retries

Revision ID: e57aa8870f80
Revises: e13e045eeb8b
Create Date: 2026-09-19 17:09:44.199516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57aa8870f80'
down_revision: Union[str, Sequence[str], None] = 'e13e045eeb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('outbox_events', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_outbox_events_unpublished_created_at'), table_name='outbox_events', postgresql_where='(published_at IS NULL)')
    op.create_index('ix_outbox_events_publishable_available_at', 'outbox_events', ['available_at', 'created_at', 'id'], unique=False, postgresql_where=sa.text('published_at IS NULL AND failed_at IS NULL'))
    op.create_check_constraint('outbox_events_not_published_and_failed_check', 'outbox_events', 'NOT (published_at IS NOT NULL AND failed_at IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('outbox_events_not_published_and_failed_check', 'outbox_events', type_='check')
    op.drop_index('ix_outbox_events_publishable_available_at', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL AND failed_at IS NULL'))
    op.create_index(op.f('ix_outbox_events_unpublished_created_at'), 'outbox_events', ['created_at'], unique=False, postgresql_where='(published_at IS NULL)')
    op.drop_column('outbox_events', 'failed_at')
    op.drop_column('outbox_events', 'available_at')
    # ### end Alembic commands ###
